LDLIBS=-lm
all:test1.txt test2.txt test3.txt test4.txt


test1.txt: test1
	./test1 > test1.txt

test2.txt: test2
	./test2 > test2.txt

test3.txt: test3
	./test3 > test3.txt

test4.txt: test4
	./test4 > test4.txt
